---
title: 'Calculate Percentiles and Collect Tiles for Non-Detrended time series'
author: 'Sara Lindersson'
date: '`r Sys.Date()`'
output: github_document
---

This script calculates percentiles for daily maximum (TX) and minimum (TN) temperature values, and subsequently collects the resulting tiles.

```{r libraries, warning=F, message=F, collapse=T}
library(glue)
library(knitr)
```

```{r prevent-run, include=F}
knitr::opts_chunk$set(eval = T)
```

```{r setup, include=T}
# Set working directory
knitr::opts_knit$set(root.dir = normalizePath('F:/mswx/data-processed/')) 
```

```{r parameters}
ph_in_tn <- '03/tn_tiles'
ph_in_tx <- '03/tx_tiles'

ph_out <- '07/percentiles'

# Create output directory if it doesn't exist
if (!dir.exists(ph_out)) {
  dir.create(ph_out, recursive = TRUE)
}
```

### Percentiles of TN
#### ctn10pct
```{r ctn10pct}
# Directory for tiles
ph_out_tiles <- '07/ctn10pct'

# Create output directory if it doesn't exist
if (!dir.exists(ph_out_tiles)) {
  dir.create(ph_out_tiles, recursive = TRUE)
}

# List all the .nc files in the input directory
files <- list.files(ph_in_tn, pattern = "\\.nc$", full.names = TRUE)

for (file in files) {
  # Get the file name
  file_name <- sub('^tn_', '', basename(file))
  # Define the output file path
  out_file <- file.path(ph_out_tiles, paste0("ctn10pct_", file_name))

  # Construct the CDO command to calculate the percentiles
  cmd <- paste('wsl cdo -O -b 32 -z zip_1 -ydrunpctl,10,31 [', file, '-ydrunmin,31', file, '-ydrunmax,31', file, ']', out_file)

  # Execute the CDO command
  shell(cmd = cmd)
}

# Collect tiles
inputs <- paste0(ph_out_tiles, '/ctn10pct_*.nc')
output <- file.path(ph_out, 'ctn10pct.nc')

cmd <- paste('wsl cdo -O -b 32 -z zip_1 -collgrid', inputs, output)
shell(cmd = cmd)
```

#### ctn05pct
```{r ctn05pct}
# Directory for tiles
ph_out_tiles <- '07/ctn05pct'

# Create output directory if it doesn't exist
if (!dir.exists(ph_out_tiles)) {
  dir.create(ph_out_tiles, recursive = TRUE)
}

# List all the .nc files in the input directory
files <- list.files(ph_in_tn, pattern = "\\.nc$", full.names = TRUE)

for (file in files) {
  # Get the file name
  file_name <- sub('^tn_', '', basename(file))
  # Define the output file path
  out_file <- file.path(ph_out_tiles, paste0("ctn05pct_", file_name))
  
  # Construct the CDO command to calculate the percentiles
  cmd <- paste('wsl cdo -O -b 32 -z zip_1 -ydrunpctl,5,31 [', file, '-ydrunmin,31', file, '-ydrunmax,31', file, ']', out_file)
  
  # Execute the CDO command
  shell(cmd = cmd)
}

# Collect tiles
inputs <- paste0(ph_out_tiles, '/ctn05pct_*.nc')
output <- file.path(ph_out, 'ctn05pct.nc')

cmd <- paste('wsl cdo -O -b 32 -z zip_1 -collgrid', inputs, output)
shell(cmd = cmd)
```

### Percentiles of TX
#### ctx90pct
```{r ctx90pct}
# Directory for tiles
ph_out_tiles <- '07/ctx90pct'

# Create output directory if it doesn't exist
if (!dir.exists(ph_out_tiles)) {
  dir.create(ph_out_tiles, recursive = TRUE)
}

# List all the .nc files in the input directory
files <- list.files(ph_in_tx, pattern = "\\.nc$", full.names = TRUE)

for (file in files) {
  # Get the file name
  file_name <- sub('^tx_', '', basename(file))
  # Define the output file path
  out_file <- file.path(ph_out_tiles, paste0("ctx90pct_", file_name))
  
  # Construct the CDO command to calculate the percentiles
  cmd <- paste('wsl cdo -O -b 32 -z zip_1 -ydrunpctl,90,31 [', file, '-ydrunmin,31', file, '-ydrunmax,31', file, ']', out_file)
  
  # Execute the CDO command
  shell(cmd = cmd)
}

# Collect tiles
inputs <- paste0(ph_out_tiles, '/ctx90pct_*.nc')
output <- file.path(ph_out, 'ctx90pct.nc')

cmd <- paste('wsl cdo -O -b 32 -z zip_1 -collgrid', inputs, output)
shell(cmd = cmd)
```

#### ctx95pct
```{r ctx95pct}
# Directory for tiles
ph_out_tiles <- '07/ctx95pct'

# Create output directory if it doesn't exist
if (!dir.exists(ph_out_tiles)) {
  dir.create(ph_out_tiles, recursive = TRUE)
}

# List all the .nc files in the input directory
files <- list.files(ph_in_tx, pattern = "\\.nc$", full.names = TRUE)

for (file in files) {
  # Get the file name
  file_name <- sub('^tx_', '', basename(file))
  # Define the output file path
  out_file <- file.path(ph_out_tiles, paste0("ctx95pct_", file_name))
  
  # Construct the CDO command to calculate the percentiles
  cmd <- paste('wsl cdo -O -b 32 -z zip_1 -ydrunpctl,95,31 [', file, '-ydrunmin,31', file, '-ydrunmax,31', file, ']', out_file)
  
  # Execute the CDO command
  shell(cmd = cmd)
}

# Collect tiles
inputs <- paste0(ph_out_tiles, '/ctx95pct_*.nc')
output <- file.path(ph_out, 'ctx95pct.nc')

cmd <- paste('wsl cdo -O -b 32 -z zip_1 -collgrid', inputs, output)
shell(cmd = cmd)
```
End of script.