---
title: "Concatenate and Tile Files"
author: 'Sara Lindersson'
date: '`r Sys.Date()`'
output: github_document
---

This script concatenates and tiles yearly files containing daily maximum (TX) and minimum (TN) temperature data.

```{r libraries, warning=F, message=F, collapse=T}
library(glue)
library(knitr)
```

```{r prevent-run, include=F}
knitr::opts_chunk$set(eval = F)
```

```{r setup, include=T}
# Set working directory
knitr::opts_knit$set(root.dir = normalizePath('F:/mswx/data-processed/')) 
```

```{r parameters}
tx_input_files <- '02/tx/tx_*.nc'
tx_obase <- '03/tx_tiles/tx_'
tn_input_files <- '02/tn/tn_*.nc'
tn_obase <- '03/tn_tiles/tn_'
```

```{r data-processing}
# Create the CDO command for TX files
tx_command <- glue(
  'cdo -O -z zip_1 -b 32 -distgrid,24,12 -cat [ {tx_input_files} ] {tx_obase}'
)

# Create the CDO command for TN files
tn_command <- glue(
  'cdo -O -z zip_1 -b 32 -distgrid,24,12 -cat [ {tn_input_files} ] {tn_obase}'
)

# Run the CDO commands
system(tx_command)
system(tn_command)
```
End of script.